name: arb_translator
description: A command-line utility which helps to translate arb files with the
  use of google translations.
version: 2.0.1
homepage: https://github.com/justkawal/arb_translator.git

environment:
  sdk: ">=2.16.1 <4.0.0"

dependencies:
  args: ^2.4.0
  collection: ^1.17.0
  console: ^4.1.0
  html_unescape: ^2.0.0
  http: ^0.13.5
  path: ^1.8.2
  petitparser: ^5.1.0
  yaml: ^3.1.1
dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
